# ---------- Base image ----------
FROM python:3.12-slim

# ---------- Set working directory ----------
WORKDIR /app

# ---------- Install dependencies ----------
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# ---------- Copy project files ----------
COPY . .

# ---------- Expose FastAPI port ----------
EXPOSE 5050

# ---------- Run FastAPI ----------
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5050", "--reload"]
