# backend/models/companion.py

from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    Boolean,
    ForeignKey,
    DateTime,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.orm import relationship

from database import Base


class AICompanion(Base):
    __tablename__ = "ai_companions"

    id = Column(Integer, primary_key=True, index=True)

    # ====== UI display fields ======
    # UI name (e.g., Luna / Sol / Terra)
    name = Column(String(50), nullable=False)

    # Internal key (used in code/prompt, e.g., luna/sol/terra)
    key = Column(String(50), unique=True, nullable=False)

    # Role title (e.g., Your Gentle Companion)
    identity_title = Column(String(100), nullable=False)

    # Description paragraph below the card (user-facing)
    description = Column(Text, nullable=False)

    # A few tags (user-facing personality tags)
    tags = Column(ARRAY(String), nullable=False)

    # Illustration key (frontend asset)
    avatar_key = Column(String(50), nullable=True)

    # Background color, e.g. "#FFD47D"
    theme_color = Column(String(20), nullable=True)

    # Sort order (list display)
    order_index = Column(Integer, nullable=False, server_default="0")

    # ====== Source: system preset or custom ======
    # System preset: created_by_user_id = NULL
    # User custom: created_by_user_id = some user.id
    created_by_user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=True,
        index=True,
    )

    # Enabled flag (soft-delete/unlist)
    is_active = Column(Boolean, nullable=False, server_default="true")

    # ====== LLM behavior config (for the model) ======
    # Full persona description for LLM (long text)
    persona_prompt = Column(Text, nullable=True)

    # Reply length preference: short / medium / long
    reply_length_hint = Column(
        String(20),
        nullable=False,
        server_default="medium",
    )

    # Whether this AI can provide advice-like content
    allow_suggestions = Column(
        Boolean,
        nullable=False,
        server_default="true",
    )

    # ====== Admin fields ======
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # ====== Relationships (User / AIReply) ======

    # User who created this custom AI (system preset is NULL)
    creator = relationship(
        "User",
        back_populates="custom_companions",
        foreign_keys=[created_by_user_id],
    )

    # Users who selected this as current companion (many-to-one reverse)
    selected_by_users = relationship(
        "User",
        back_populates="companion",
        foreign_keys="User.companion_id",
    )

    # Replies generated by this AI
    replies = relationship(
        "AIReply",
        back_populates="companion",
    )
