from pydantic import BaseModel
from datetime import datetime
from typing import Optional, Literal, Dict


# -------------------------------
# Theme type (primary theme)
# -------------------------------
EntryTheme = Literal["work", "hobbies", "social", "other"]


# -------------------------------
# AI reply output (to frontend)
# -------------------------------
class AIReplyOut(BaseModel):
    id: int
    entry_id: int
    companion_id: int          # Which AI companion replied
    reply_type: str            # Currently "empathetic_reply_with_emotion"
    content: str               # Actual reply text
    model_name: Optional[str] = None
    created_at: datetime

    class Config:
        from_attributes = True


# -------------------------------
# Create journal entry (frontend input)
# Only needs content + whether AI reply is required
# Theme is generated by backend analysis, not from frontend
# -------------------------------
class EntryCreate(BaseModel):
    content: str
    need_ai_reply: bool = False


# -------------------------------
# List page summary data
# -------------------------------
class EntrySummary(BaseModel):
    id: int
    summary: str
    created_at: datetime
    emotion: Optional[str]

    # Primary theme
    primary_theme: Optional[EntryTheme] = None

    class Config:
        from_attributes = True


# -------------------------------
# Detail page (full output)
# -------------------------------
class EntryOut(BaseModel):
    id: int
    user_id: int
    content: str
    summary: Optional[str]
    created_at: datetime

    emotion: Optional[str]
    emotion_intensity: Optional[int]

    # Primary theme (quick display/filter)
    primary_theme: Optional[EntryTheme] = None

    # Theme score distribution (for insights aggregation)
    # Example: {"work":0.2,"hobbies":0.5,"social":0.1,"other":0.2}
    theme_scores: Optional[Dict[str, float]] = None

    # Now an object, not a string
    ai_reply: Optional[AIReplyOut] = None

    # Pleasure score (computed dynamically)
    pleasure: float

    class Config:
        from_attributes = True
